/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TimePlace } from '../models/time-place';
export interface Flight {
  airline?: string | null;
  arrival?: TimePlace;
  departure?: TimePlace;
  id?: string;
  price?: string | null;
  remaingNumberOfSeat?: number;
  remainingNumberOfSeats?: number;
}
