/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { BookDto } from './models/book-dto';
export { BookingRm } from './models/booking-rm';
export { Flight } from './models/flight';
export { FlightRm } from './models/flight-rm';
export { NewPassengerDto } from './models/new-passenger-dto';
export { PassengerRm } from './models/passenger-rm';
export { ProblemDetails } from './models/problem-details';
export { TimePlace } from './models/time-place';
export { TimePlaceRm } from './models/time-place-rm';
